### ISSUE TITLE
error code, whats the problem?

### ISSUE THREAD

**Issue by Siddharth-Selvarajan** [BurnhamG/packtpub-downloader#14]
![image](https://user-images.githubusercontent.com/69203685/91742174-73b3a000-ebd3-11ea-846a-62e8b1680113.png)

**Comment by BurnhamG** [comment]
Hi, Siddarth, it looks like one of the books that was downloaded in the past isn't available through the API anymore, and that's why you're getting an error. I have written code to handle this issue, so I'll update the master branch with that code in the next couple of days once I can make sure that it's truly ready to go. If you're willing to try the updated code before it's merged over, you can use the async branch.

**Comment by Siddharth-Selvarajan** [comment]
sure, thank you.
